# Generated by Django 4.2.7 on 2024-10-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id_tarifa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_entrada', models.DateTimeField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.usuariofrecuente')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id_transaccion', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_tarifa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.tarifa')),
                ('id_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.vehiculo')),
            ],
        ),
    ]
