# Generated by Django 4.2.7 on 2024-10-08 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_tarifa_transaccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarifa',
            name='tipo_tarifa',
            field=models.CharField(choices=[('Pagar día', 'Pagar día'), ('Pagar hora', 'Pagar hora'), ('Recargar saldo', 'Recargar saldo')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
