# Generated by Django 4.2.7 on 2024-10-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_tarifa_tipo_tarifa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='id_vehicle',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='tipo_tarifa',
            field=models.CharField(choices=[('Pagar día', 'Pagar día'), ('Pagar hora', 'Pagar hora'), ('Recargar saldo', 'Recargar saldo')], default='Pagar día', max_length=20),
        ),
    ]
