# Generated by Django 4.2.7 on 2024-10-08 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_remove_tarifa_id_usuario_remove_tarifa_id_vehicle_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarifa',
            old_name='cost',
            new_name='valor',
        ),
        migrations.RenameField(
            model_name='transaccion',
            old_name='costo',
            new_name='valor',
        ),
        migrations.AddField(
            model_name='tarifa',
            name='id_usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.usuariofrecuente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarifa',
            name='id_vehicle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parking.vehiculo'),
            preserve_default=False,
        ),
    ]
