# Generated by Django 4.2.7 on 2024-10-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_rename_valor_tarifa_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='fecha_entrada',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='tarifa',
            name='id_vehicle',
        ),
        migrations.RemoveField(
            model_name='transaccion',
            name='valor',
        ),
        migrations.AlterField(
            model_name='tarifa',
            name='id_tarifa',
            field=models.CharField(choices=[('Pagar día', 'Pagar día'), ('Pagar hora', 'Pagar hora'), ('Recargar saldo', 'Recargar saldo')], max_length=20, primary_key=True, serialize=False),
        ),
    ]
