# Generated by Django 4.2.7 on 2024-10-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_remove_tarifa_fecha_entrada_remove_tarifa_id_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarifa',
            name='tipo_tarifa',
        ),
    ]
